### ISSUE TITLE
Server returned HTTP response code: 403 for URL: http://timestamp.entrust.net/TSS/RFC3161sha2TS/chain.pem

### ISSUE THREAD

**Issue by LukeSesame** [elbosso/rfc3161client#1] opened 2021-04-06 10:44 UTC
Hi...sorry to bother you but i encoutered some issues when running the project...I tried to timeStamp a file with "http://timestamp.entrust.net/TSS/RFC3161sha2TS" but it returned me this error  <<<<Server returned HTTP response code: 403 for URL: http://timestamp.entrust.net/TSS/RFC3161sha2TS/chain.pem >>>>.
Could you help me please?
sorry for my english, i'm french!

**Comment by elbosso** [comment] 2021-04-06 16:35
OK, lets get down to it:

The error you got was caused by trying to get the certificate chain with the name as it would be for my other project 
https://github.com/elbosso/rfc3161timestampingserver - but you used a different server and it would be highly unlikely that the admins of a different server would name the chain file exactly as i did.

The chain is needed to establish trust - this example project offers a way to specify an additional trust anchor by putting in the chain. If you use a "official" TSA that got iths certificate from a trusted root already in the JRE, you would not need the chain.

I added an example for this scenario in the source as well as i added some more comments that should make those things clearer (i hope). But - if you rely on the trust anchors coming with the CA - there is currently a drawback: All those trust anchors are examined in turen and their CRLs are downloaded. This can be a time-consuming job. From that Point of view it would still be better to explicitely specify a trusted root (In the case of entrust, this would be the root certificate).

I added that specific example as well (it is the only one currently not commented out) and wrote a short comment for that too.

I hope, that I cleared up things a bit - however if you are still getting problems or seeing error - dont hesitate to ask...

Please note: I had to update one of the snapshot dependencies, so if you work with maven - or your IDE is - make sure to build with "-U" so that snapshot updates are fetched as well...

**Comment by elbosso** [comment] 2021-04-06 16:36
location of root certificates for entrust: https://www.entrust.com/resources/certificate-solutions/tools/root-certificate-downloads

**Comment by LukeSesame** [comment] 2021-04-09 09:25
First of all, thank you for the feedback.
Maybe i misunderstood you but i still have issues.
here is the output when i run the programm :

![Capture d’écran (110)](https://user-images.githubusercontent.com/75071159/114159429-b255c980-991d-11eb-856e-42f24df2fa99.png)

thank you for the help!

**Comment by elbosso** [comment] 2021-04-09 15:37
Ahh, yes - that null pointer comes because the snapshot release of the library was not yet updated. As i see that you are using eclipse I think you have to click on the project and the n hit ALT+F5 to trigger that update. Alternatively you could set the Log Level to WARN - that way, the code path responsible for that nullpointer is never reached.

I hope that helps - if not, please let me know!

**Comment by LukeSesame** [comment] 2021-08-17 15:06
Hello, it's me again. Sorry for disappearing but i've been assigned to another task. i follow your instructions by Updating the project but i still have the same issues.
Could you help me please ???
![Capture d’écran 2021-08-17 160624](https://user-images.githubusercontent.com/75071159/129751539-37beb934-2f7a-4b7d-9954-b506835f6410.png)

**Comment by LukeSesame** [comment] 2021-08-17 15:39
I tried with another trusted certificated and i've got this:
![Capture d’écran 2021-08-17 163750](https://user-images.githubusercontent.com/75071159/129756962-a579a318-647f-402b-874e-cd10bead3aeb.png)


Thank you for your help

**Comment by elbosso** [comment] 2021-08-22 11:56
> Hello, it's me again. Sorry for disappearing but i've been assigned to another task. i follow your instructions by Updating the project but i still have the same issues.
> Could you help me please ???
> ![Capture d’écran 2021-08-17 160624](https://user-images.githubusercontent.com/75071159/129751539-37beb934-2f7a-4b7d-9954-b506835f6410.png)

Hi, I told you last time we communicated that you have to trigger the update of artifacts in eclipse: https://github.com/elbosso/rfc3161client/issues/1#issuecomment-816769486 
The screenshot shows that you did not (successfully) do that. Please make sure to force the update of Snapshots:

![image](https://user-images.githubusercontent.com/18102857/130354137-1866a277-2177-4ec1-983c-59c219287563.png)

**Comment by elbosso** [comment] 2021-08-22 12:01
> I tried with another trusted certificated and i've got this:
> ![Capture d’écran 2021-08-17 163750](https://user-images.githubusercontent.com/75071159/129756962-a579a318-647f-402b-874e-cd10bead3aeb.png)
> 
> Thank you for your help

Hello, what you show here is the expected behaviour - the validator can not establish a chain of trust with the given certificate and thus the verification fails.

Please try the example code again with the correct certificate after updating the dependencies in eclipse using the correct certificate https://web.entrust.com/root-certificates/entrust_2048_ca.cer

I also deduce from the screenshots that you did not update the project as a whole after i checked in the fix 5 months ago  - please be sure to pull the project before trying to update the dependencies in eclipse. The current head of the project contains a little more (hopefully) helpful comments in TsaClientExample.java

**Closed** 2022-04-27 16:02 UTC
